### ISSUE TITLE
Rewriting function "prepare_text" instead of calling it

### ISSUE THREAD

**Issue by quuu** [gonzalomarcote/pwp-capstones#1]
Under the section "The Third Indicator: N-Grams",  you seem to have the answer so far to the TextSample class. In your answer, you seem to recreate "prepare_text":

`self.prepared_text = []
  prepared_text_step1 = text.lower()
  prepared_text_step2 = prepared_text_step1.replace(',', '')
  prepared_text_step3 = prepared_text_step2.replace('.', '')
  prepared_text_step4 = prepared_text_step3.replace('!', '')
  prepared_text_step5 = prepared_text_step4.replace('?', '')
  self.prepared_text = prepared_text_step5.split()
`

Instead of simply doing

`self.prepared_text = prepare_text(text)`

**Comment by gonzalomarcote** [comment]
You are totally right. Fixed.
